### ISSUE TITLE
using statement in JsonFileProductService.cs does not match video

### ISSUE THREAD

**Issue by ssaari** [dotnet-presentations/ContosoCrafts#10]
JsonFileProductService.cs includes a reference that does not match this video.  This makes the solution not recognize the Product class in Models.  Change using "ContosoCrafts.Website.Models" to using "Contoso.Models" to fix it.

**Comment by stevenyholm** [comment]
I noticed this too. It's because they named the project "ContosoCrafts.Website" in the beginning when they first created the project. By default, Visual Studio will use this name for namespaces. Renaming your project file in Visual Studio will change the default namespace that new files will get. I found the project name in the solution file (.sln) -- but don't typically edit those files because they are auto-generated.

**Comment by jamesmontemagno** [comment]
I watched through the video and I think it is all working alright as long as you name your project "ContosoCrafts.WebSite" corret...
